//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string ScheduleId { get; set; }
        public string Subject { get; set; }
        public string Days { get; set; }
        public string Time { get; set; }
        public string Room { get; set; }
        public string Teacher { get; set; }
    }
}
